//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ME.Libros.Web {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ME.Libros.Web.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El &lt;b&gt;CUIL {0}&lt;/b&gt; se encuentra asociado a un cliente existente.
        /// </summary>
        public static string CuilRepetido {
            get {
                return ResourceManager.GetString("CuilRepetido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La &lt;b&gt;{0}&lt;/b&gt; es incorrecta.
        /// </summary>
        public static string DateFormat {
            get {
                return ResourceManager.GetString("DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} no puede eliminarse porque tiene datos asociados.
        /// </summary>
        public static string DatosAsociados {
            get {
                return ResourceManager.GetString("DatosAsociados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El &lt;b&gt;{0}&lt;/b&gt; debe ser decimal.
        /// </summary>
        public static string Decimal {
            get {
                return ResourceManager.GetString("Decimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El &lt;b&gt;DNI&lt;/b&gt; {0} se encuentra asociado a un {1} existente.
        /// </summary>
        public static string DniRepetido {
            get {
                return ResourceManager.GetString("DniRepetido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El cliente no puede ser eliminado porque tiene datos asociados.
        /// </summary>
        public static string EliminarCliente {
            get {
                return ResourceManager.GetString("EliminarCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La editorial no puede ser eliminada porque tiene datos asociados.
        /// </summary>
        public static string EliminarEditorial {
            get {
                return ResourceManager.GetString("EliminarEditorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La localidad no puede ser eliminada porque tiene datos asociados.
        /// </summary>
        public static string EliminarLocalidad {
            get {
                return ResourceManager.GetString("EliminarLocalidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El rubro no puede ser eliminado porque tiene datos asociados.
        /// </summary>
        public static string EliminarRubro {
            get {
                return ResourceManager.GetString("EliminarRubro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al anular..
        /// </summary>
        public static string ErrorAnular {
            get {
                return ResourceManager.GetString("ErrorAnular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al eliminar..
        /// </summary>
        public static string ErrorEliminar {
            get {
                return ResourceManager.GetString("ErrorEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha ocurrido un error en el sistema.
        /// </summary>
        public static string ErrorSistema {
            get {
                return ResourceManager.GetString("ErrorSistema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El &lt;b&gt;{0}&lt;/b&gt; debe contener {1} caracteres.
        /// </summary>
        public static string ExactLenght {
            get {
                return ResourceManager.GetString("ExactLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La &lt;b&gt;{0}&lt;/b&gt; es inválida.
        /// </summary>
        public static string Invalida {
            get {
                return ResourceManager.GetString("Invalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El formato del email no es correcto.
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El &lt;b&gt;{0}&lt;/b&gt; es inválido.
        /// </summary>
        public static string Invalido {
            get {
                return ResourceManager.GetString("Invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El formato del teléfono no es correcto.
        /// </summary>
        public static string InvalidTel {
            get {
                return ResourceManager.GetString("InvalidTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario o contraseña suministradas son incorrectas..
        /// </summary>
        public static string InvalidUserPassword {
            get {
                return ResourceManager.GetString("InvalidUserPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El &lt;b&gt;{0}&lt;/b&gt; debe ser numerico.
        /// </summary>
        public static string Numeric {
            get {
                return ResourceManager.GetString("Numeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El &lt;b&gt;{0}&lt;/b&gt; debe contener solo letras.
        /// </summary>
        public static string OnlyLetters {
            get {
                return ResourceManager.GetString("OnlyLetters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El &lt;b&gt;{0}&lt;/b&gt; debe contener solo números.
        /// </summary>
        public static string OnlyNumbers {
            get {
                return ResourceManager.GetString("OnlyNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las contraseñas no coinciden.
        /// </summary>
        public static string PasswordEquals {
            get {
                return ResourceManager.GetString("PasswordEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El &lt;b&gt;{0}&lt;/b&gt; debe contener entre {1} y {2} caracteres.
        /// </summary>
        public static string RangeLenght {
            get {
                return ResourceManager.GetString("RangeLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo &lt;b&gt;{0}&lt;/b&gt; es requerido.
        /// </summary>
        public static string RepetirPasswordRequerido {
            get {
                return ResourceManager.GetString("RepetirPasswordRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La &lt;b&gt;{0}&lt;/b&gt; es requerida.
        /// </summary>
        public static string Requerida {
            get {
                return ResourceManager.GetString("Requerida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El &lt;b&gt;{0}&lt;/b&gt; es requerido.
        /// </summary>
        public static string Requerido {
            get {
                return ResourceManager.GetString("Requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El stock disponible de &lt;b&gt;{0}&lt;/b&gt; es de {1} unidades..
        /// </summary>
        public static string Stock {
            get {
                return ResourceManager.GetString("Stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El &lt;b&gt;{0}&lt;/b&gt; debe contener {1} caracteres como máximo.
        /// </summary>
        public static string StringLength {
            get {
                return ResourceManager.GetString("StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña debe tener al menos 8 caracteres.
        /// </summary>
        public static string StringMinLength {
            get {
                return ResourceManager.GetString("StringMinLength", resourceCulture);
            }
        }
    }
}
