//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ME.Libros.Web {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ME.Libros.Web.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El &lt;b&gt;Codigo de Barra {0}&lt;/b&gt; ya se encuentra asociado a un producto existente.
        /// </summary>
        public static string CodigoBarraRepetido {
            get {
                return ResourceManager.GetString("CodigoBarraRepetido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El &lt;b&gt;CUIL {0}&lt;/b&gt; se encuentra asociado a un cliente existente.
        /// </summary>
        public static string CuilRepetido {
            get {
                return ResourceManager.GetString("CuilRepetido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La &lt;b&gt;{0}&lt;/b&gt; es incorrecta.
        /// </summary>
        public static string DateFormat {
            get {
                return ResourceManager.GetString("DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} no puede eliminarse porque tiene datos asociados.
        /// </summary>
        public static string DatosAsociados {
            get {
                return ResourceManager.GetString("DatosAsociados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El &lt;b&gt;{0}&lt;/b&gt; debe ser decimal.
        /// </summary>
        public static string Decimal {
            get {
                return ResourceManager.GetString("Decimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El &lt;b&gt;DNI {0} &lt;/b&gt; se encuentra asociado a un {1} existente.
        /// </summary>
        public static string DniRepetido {
            get {
                return ResourceManager.GetString("DniRepetido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El cliente no puede ser eliminado porque tiene datos asociados.
        /// </summary>
        public static string EliminarCliente {
            get {
                return ResourceManager.GetString("EliminarCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La editorial no puede ser eliminada porque tiene datos asociados.
        /// </summary>
        public static string EliminarEditorial {
            get {
                return ResourceManager.GetString("EliminarEditorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La localidad no puede ser eliminada porque tiene datos asociados.
        /// </summary>
        public static string EliminarLocalidad {
            get {
                return ResourceManager.GetString("EliminarLocalidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El rubro no puede ser eliminado porque tiene datos asociados.
        /// </summary>
        public static string EliminarRubro {
            get {
                return ResourceManager.GetString("EliminarRubro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El &lt;b&gt;{0}&lt;/b&gt; debe ser un número entero.
        /// </summary>
        public static string Entero {
            get {
                return ResourceManager.GetString("Entero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al anular.
        /// </summary>
        public static string ErrorAnular {
            get {
                return ResourceManager.GetString("ErrorAnular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al eliminar.
        /// </summary>
        public static string ErrorEliminar {
            get {
                return ResourceManager.GetString("ErrorEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error en el sistema.
        /// </summary>
        public static string ErrorSistema {
            get {
                return ResourceManager.GetString("ErrorSistema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El &lt;b&gt;{0}&lt;/b&gt; debe contener {1} caracteres.
        /// </summary>
        public static string ExactLenght {
            get {
                return ResourceManager.GetString("ExactLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La &lt;b&gt;{0}&lt;/b&gt; es inválida.
        /// </summary>
        public static string Invalida {
            get {
                return ResourceManager.GetString("Invalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El formato del &lt;b&gt;{0}&lt;/b&gt; no es correcto.
        /// </summary>
        public static string InvalidCuil {
            get {
                return ResourceManager.GetString("InvalidCuil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El formato del &lt;b&gt;{0}&lt;/b&gt; no es correcto.
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El &lt;b&gt;{0}&lt;/b&gt; es inválido.
        /// </summary>
        public static string Invalido {
            get {
                return ResourceManager.GetString("Invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El formato del &lt;b&gt;{0}&lt;/b&gt; no es correcto.
        /// </summary>
        public static string InvalidTel {
            get {
                return ResourceManager.GetString("InvalidTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario o contraseña suministradas son incorrectas..
        /// </summary>
        public static string InvalidUserPassword {
            get {
                return ResourceManager.GetString("InvalidUserPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El &lt;b&gt;{0}&lt;/b&gt; debe contener solo letras.
        /// </summary>
        public static string OnlyLetters {
            get {
                return ResourceManager.GetString("OnlyLetters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El &lt;b&gt;{0}&lt;/b&gt; debe contener solo números.
        /// </summary>
        public static string OnlyNumbers {
            get {
                return ResourceManager.GetString("OnlyNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las contraseñas no coinciden.
        /// </summary>
        public static string PasswordEquals {
            get {
                return ResourceManager.GetString("PasswordEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El &lt;b&gt;{0}&lt;/b&gt; debe contener entre {1} y {2} caracteres.
        /// </summary>
        public static string RangeLenght {
            get {
                return ResourceManager.GetString("RangeLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El &lt;b&gt;{0}&lt;/b&gt; esta fuera de rango. Rango permitido: [{1} ; {2}].
        /// </summary>
        public static string RangeValue {
            get {
                return ResourceManager.GetString("RangeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo &lt;b&gt;{0}&lt;/b&gt; es requerido.
        /// </summary>
        public static string RepetirPasswordRequerido {
            get {
                return ResourceManager.GetString("RepetirPasswordRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La &lt;b&gt;{0}&lt;/b&gt; es requerida.
        /// </summary>
        public static string Requerida {
            get {
                return ResourceManager.GetString("Requerida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El &lt;b&gt;{0}&lt;/b&gt; es requerido.
        /// </summary>
        public static string Requerido {
            get {
                return ResourceManager.GetString("Requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El stock disponible de &lt;b&gt;{0}&lt;/b&gt; es de {1} unidades..
        /// </summary>
        public static string Stock {
            get {
                return ResourceManager.GetString("Stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El &lt;b&gt;{0}&lt;/b&gt; debe contener {1} caracteres como máximo.
        /// </summary>
        public static string StringLength {
            get {
                return ResourceManager.GetString("StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña debe tener al menos 8 caracteres.
        /// </summary>
        public static string StringMinLength {
            get {
                return ResourceManager.GetString("StringMinLength", resourceCulture);
            }
        }
    }
}
