//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ME.Libros.Web {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ME.Libros.Web.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente.
        /// </summary>
        public static string Cliente {
            get {
                return ResourceManager.GetString("Cliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código.
        /// </summary>
        public static string Codigo {
            get {
                return ResourceManager.GetString("Codigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Codigo de barra.
        /// </summary>
        public static string CodigoBarra {
            get {
                return ResourceManager.GetString("CodigoBarra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CUIL/CUIT.
        /// </summary>
        public static string Cuil {
            get {
                return ResourceManager.GetString("Cuil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        public static string Descripcion {
            get {
                return ResourceManager.GetString("Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dirección.
        /// </summary>
        public static string Direccion {
            get {
                return ResourceManager.GetString("Direccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editorial.
        /// </summary>
        public static string Editorial {
            get {
                return ResourceManager.GetString("Editorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El cliente.
        /// </summary>
        public static string ElCliente {
            get {
                return ResourceManager.GetString("ElCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El producto.
        /// </summary>
        public static string ElProducto {
            get {
                return ResourceManager.GetString("ElProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El rubro.
        /// </summary>
        public static string ElRubro {
            get {
                return ResourceManager.GetString("ElRubro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Nº {1} se eliminó exitosamente.
        /// </summary>
        public static string EntidadEliminada {
            get {
                return ResourceManager.GetString("EntidadEliminada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Nº {1} se modificó exitosamente.
        /// </summary>
        public static string EntidadModificada {
            get {
                return ResourceManager.GetString("EntidadModificada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} N° {1} se creó exitosamente.
        /// </summary>
        public static string EntidadNueva {
            get {
                return ResourceManager.GetString("EntidadNueva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha.
        /// </summary>
        public static string Fecha {
            get {
                return ResourceManager.GetString("Fecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de alta.
        /// </summary>
        public static string FechaAlta {
            get {
                return ResourceManager.GetString("FechaAlta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de vencimiento.
        /// </summary>
        public static string FechaCobro {
            get {
                return ResourceManager.GetString("FechaCobro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de nacimiento.
        /// </summary>
        public static string FechaNacimiento {
            get {
                return ResourceManager.GetString("FechaNacimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La {0}.
        /// </summary>
        public static string Fentidad {
            get {
                return ResourceManager.GetString("Fentidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La editorial.
        /// </summary>
        public static string LaEditorial {
            get {
                return ResourceManager.GetString("LaEditorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La localidad.
        /// </summary>
        public static string LaLocalidad {
            get {
                return ResourceManager.GetString("LaLocalidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La zona.
        /// </summary>
        public static string LaZona {
            get {
                return ResourceManager.GetString("LaZona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Localidad.
        ///   Looks up a localized string similar to Localidad.
        /// </summary>
        public static string Localidad {
            get {
                return ResourceManager.GetString("Localidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El {0}.
        /// </summary>
        public static string Mentidad {
            get {
                return ResourceManager.GetString("Mentidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nº.
        /// </summary>
        public static string Numero {
            get {
                return ResourceManager.GetString("Numero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Precio de costo.
        /// </summary>
        public static string PrecioCosto {
            get {
                return ResourceManager.GetString("PrecioCosto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Precio de venta.
        /// </summary>
        public static string PrecioVenta {
            get {
                return ResourceManager.GetString("PrecioVenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Provincia.
        /// </summary>
        public static string Provincia {
            get {
                return ResourceManager.GetString("Provincia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rubro.
        /// </summary>
        public static string Rubro {
            get {
                return ResourceManager.GetString("Rubro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Stock.
        /// </summary>
        public static string Stock {
            get {
                return ResourceManager.GetString("Stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfono fijo.
        /// </summary>
        public static string TelefonoFijo {
            get {
                return ResourceManager.GetString("TelefonoFijo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Zona.
        /// </summary>
        public static string Zona {
            get {
                return ResourceManager.GetString("Zona", resourceCulture);
            }
        }
    }
}
