//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ME.Libros.Web {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ME.Libros.Web.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alicuota.
        /// </summary>
        public static string Alicuota {
            get {
                return ResourceManager.GetString("Alicuota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantidad de cuotas.
        /// </summary>
        public static string CantidadCuotas {
            get {
                return ResourceManager.GetString("CantidadCuotas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celular Alternativo.
        /// </summary>
        public static string Celular2 {
            get {
                return ResourceManager.GetString("Celular2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente.
        /// </summary>
        public static string Cliente {
            get {
                return ResourceManager.GetString("Cliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cobrador.
        /// </summary>
        public static string Cobrador {
            get {
                return ResourceManager.GetString("Cobrador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código.
        /// </summary>
        public static string Codigo {
            get {
                return ResourceManager.GetString("Codigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codigo de barra.
        /// </summary>
        public static string CodigoBarra {
            get {
                return ResourceManager.GetString("CodigoBarra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CP.
        /// </summary>
        public static string CodigoPostal {
            get {
                return ResourceManager.GetString("CodigoPostal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repetir contraseña.
        /// </summary>
        public static string ConfirmarPassword {
            get {
                return ResourceManager.GetString("ConfirmarPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CUIT.
        /// </summary>
        public static string Cuil {
            get {
                return ResourceManager.GetString("Cuil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        public static string Descripcion {
            get {
                return ResourceManager.GetString("Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirección.
        /// </summary>
        public static string Direccion {
            get {
                return ResourceManager.GetString("Direccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DNI.
        /// </summary>
        public static string Dni {
            get {
                return ResourceManager.GetString("Dni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editorial.
        /// </summary>
        public static string Editorial {
            get {
                return ResourceManager.GetString("Editorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El cliente.
        /// </summary>
        public static string ElCliente {
            get {
                return ResourceManager.GetString("ElCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El cobrador.
        /// </summary>
        public static string ElCobrador {
            get {
                return ResourceManager.GetString("ElCobrador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El cobro.
        /// </summary>
        public static string ElCobro {
            get {
                return ResourceManager.GetString("ElCobro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El gasto.
        /// </summary>
        public static string ElGasto {
            get {
                return ResourceManager.GetString("ElGasto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Iva.
        /// </summary>
        public static string ElIva {
            get {
                return ResourceManager.GetString("ElIva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Login.
        /// </summary>
        public static string ElLogin {
            get {
                return ResourceManager.GetString("ElLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El plan de pago.
        /// </summary>
        public static string ElPlanPago {
            get {
                return ResourceManager.GetString("ElPlanPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El producto.
        /// </summary>
        public static string ElProducto {
            get {
                return ResourceManager.GetString("ElProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El proveedor.
        /// </summary>
        public static string ElProveedor {
            get {
                return ResourceManager.GetString("ElProveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El rubro.
        /// </summary>
        public static string ElRubro {
            get {
                return ResourceManager.GetString("ElRubro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Usuario.
        /// </summary>
        public static string ElUsuario {
            get {
                return ResourceManager.GetString("ElUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El vendedor.
        /// </summary>
        public static string ElVendedor {
            get {
                return ResourceManager.GetString("ElVendedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email confirmado.
        /// </summary>
        public static string EmailConfirmado {
            get {
                return ResourceManager.GetString("EmailConfirmado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Nº {1} se anuló exitosamente.
        /// </summary>
        public static string EntidadAnulada {
            get {
                return ResourceManager.GetString("EntidadAnulada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Nº {1} se eliminó exitosamente.
        /// </summary>
        public static string EntidadEliminada {
            get {
                return ResourceManager.GetString("EntidadEliminada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Nº {1} se modificó exitosamente.
        /// </summary>
        public static string EntidadModificada {
            get {
                return ResourceManager.GetString("EntidadModificada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} N° {1} se creó exitosamente.
        /// </summary>
        public static string EntidadNueva {
            get {
                return ResourceManager.GetString("EntidadNueva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de alta.
        /// </summary>
        public static string FechaAlta {
            get {
                return ResourceManager.GetString("FechaAlta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cobrada.
        /// </summary>
        public static string FechaCobrada {
            get {
                return ResourceManager.GetString("FechaCobrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de cobro.
        /// </summary>
        public static string FechaCobro {
            get {
                return ResourceManager.GetString("FechaCobro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de compra.
        /// </summary>
        public static string FechaCompra {
            get {
                return ResourceManager.GetString("FechaCompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de nacimiento.
        /// </summary>
        public static string FechaNacimiento {
            get {
                return ResourceManager.GetString("FechaNacimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vencimiento.
        /// </summary>
        public static string FechaVencimiento {
            get {
                return ResourceManager.GetString("FechaVencimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de venta.
        /// </summary>
        public static string FechaVenta {
            get {
                return ResourceManager.GetString("FechaVenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La {0}.
        /// </summary>
        public static string Fentidad {
            get {
                return ResourceManager.GetString("Fentidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gasto.
        /// </summary>
        public static string Gasto {
            get {
                return ResourceManager.GetString("Gasto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iva.
        /// </summary>
        public static string Iva {
            get {
                return ResourceManager.GetString("Iva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La compra.
        /// </summary>
        public static string LaCompra {
            get {
                return ResourceManager.GetString("LaCompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La editorial.
        /// </summary>
        public static string LaEditorial {
            get {
                return ResourceManager.GetString("LaEditorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La localidad.
        /// </summary>
        public static string LaLocalidad {
            get {
                return ResourceManager.GetString("LaLocalidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La rendición.
        /// </summary>
        public static string LaRendicion {
            get {
                return ResourceManager.GetString("LaRendicion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La venta.
        /// </summary>
        public static string LaVenta {
            get {
                return ResourceManager.GetString("LaVenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La zona.
        /// </summary>
        public static string LaZona {
            get {
                return ResourceManager.GetString("LaZona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localidad.
        /// </summary>
        public static string Localidad {
            get {
                return ResourceManager.GetString("Localidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localidades Asignadas.
        /// </summary>
        public static string LocalidadesAsignadas {
            get {
                return ResourceManager.GetString("LocalidadesAsignadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El {0}.
        /// </summary>
        public static string Mentidad {
            get {
                return ResourceManager.GetString("Mentidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monto calculado.
        /// </summary>
        public static string MontoCalculado {
            get {
                return ResourceManager.GetString("MontoCalculado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cobrado.
        /// </summary>
        public static string MontoCobrado {
            get {
                return ResourceManager.GetString("MontoCobrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monto.
        /// </summary>
        public static string MontoCobro {
            get {
                return ResourceManager.GetString("MontoCobro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monto cobrado.
        /// </summary>
        public static string MontoCobroCuota {
            get {
                return ResourceManager.GetString("MontoCobroCuota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comision.
        /// </summary>
        public static string MontoComision {
            get {
                return ResourceManager.GetString("MontoComision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monto.
        /// </summary>
        public static string MontoComprado {
            get {
                return ResourceManager.GetString("MontoComprado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monto original.
        /// </summary>
        public static string MontoCuota {
            get {
                return ResourceManager.GetString("MontoCuota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monto facturado.
        /// </summary>
        public static string MontoFacturado {
            get {
                return ResourceManager.GetString("MontoFacturado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtotal calculado.
        /// </summary>
        public static string MontoItemCalculado {
            get {
                return ResourceManager.GetString("MontoItemCalculado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtotal.
        /// </summary>
        public static string MontoItemComprado {
            get {
                return ResourceManager.GetString("MontoItemComprado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtotal vendido.
        /// </summary>
        public static string MontoItemVendido {
            get {
                return ResourceManager.GetString("MontoItemVendido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monto neto.
        /// </summary>
        public static string MontoNeto {
            get {
                return ResourceManager.GetString("MontoNeto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monto neto vendido.
        /// </summary>
        public static string MontoNetoVendido {
            get {
                return ResourceManager.GetString("MontoNetoVendido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monto vendido.
        /// </summary>
        public static string MontoVendido {
            get {
                return ResourceManager.GetString("MontoVendido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nro.
        /// </summary>
        public static string Nro {
            get {
                return ResourceManager.GetString("Nro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nº Cuota.
        /// </summary>
        public static string NroCuota {
            get {
                return ResourceManager.GetString("NroCuota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nº factura.
        /// </summary>
        public static string NroFactura {
            get {
                return ResourceManager.GetString("NroFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nº remito.
        /// </summary>
        public static string NroRemito {
            get {
                return ResourceManager.GetString("NroRemito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nº.
        /// </summary>
        public static string Numero {
            get {
                return ResourceManager.GetString("Numero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nº compra.
        /// </summary>
        public static string NumeroCompra {
            get {
                return ResourceManager.GetString("NumeroCompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nº venta.
        /// </summary>
        public static string NumeroVenta {
            get {
                return ResourceManager.GetString("NumeroVenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan de pago.
        /// </summary>
        public static string PlanPago {
            get {
                return ResourceManager.GetString("PlanPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comisión (%).
        /// </summary>
        public static string PorcentajeComision {
            get {
                return ResourceManager.GetString("PorcentajeComision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio de compra.
        /// </summary>
        public static string PrecioCompra {
            get {
                return ResourceManager.GetString("PrecioCompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio de costo.
        /// </summary>
        public static string PrecioCosto {
            get {
                return ResourceManager.GetString("PrecioCosto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio de costo anterior.
        /// </summary>
        public static string PrecioCostoAnterior {
            get {
                return ResourceManager.GetString("PrecioCostoAnterior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio de costo.
        /// </summary>
        public static string PrecioCostoComprado {
            get {
                return ResourceManager.GetString("PrecioCostoComprado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio de venta.
        /// </summary>
        public static string PrecioVenta {
            get {
                return ResourceManager.GetString("PrecioVenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio de venta calculado.
        /// </summary>
        public static string PrecioVentaCalculado {
            get {
                return ResourceManager.GetString("PrecioVentaCalculado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio de venta vendido.
        /// </summary>
        public static string PrecioVentaVendido {
            get {
                return ResourceManager.GetString("PrecioVentaVendido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Producto.
        /// </summary>
        public static string Producto {
            get {
                return ResourceManager.GetString("Producto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proveedor.
        /// </summary>
        public static string Proveedor {
            get {
                return ResourceManager.GetString("Proveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provincia.
        /// </summary>
        public static string Provincia {
            get {
                return ResourceManager.GetString("Provincia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recordarme?.
        /// </summary>
        public static string Recordarme {
            get {
                return ResourceManager.GetString("Recordarme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rubro.
        /// </summary>
        public static string Rubro {
            get {
                return ResourceManager.GetString("Rubro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saldo.
        /// </summary>
        public static string Saldo {
            get {
                return ResourceManager.GetString("Saldo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saldo.
        /// </summary>
        public static string SaldoCuota {
            get {
                return ResourceManager.GetString("SaldoCuota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock.
        /// </summary>
        public static string Stock {
            get {
                return ResourceManager.GetString("Stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teléfono fijo.
        /// </summary>
        public static string TelefonoFijo {
            get {
                return ResourceManager.GetString("TelefonoFijo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de usuario.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario.
        /// </summary>
        public static string Usuario {
            get {
                return ResourceManager.GetString("Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendedor.
        /// </summary>
        public static string Vendedor {
            get {
                return ResourceManager.GetString("Vendedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venta.
        /// </summary>
        public static string Venta {
            get {
                return ResourceManager.GetString("Venta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zona.
        /// </summary>
        public static string Zona {
            get {
                return ResourceManager.GetString("Zona", resourceCulture);
            }
        }
    }
}
